CREATE TABLE `agreements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`agreementType` enum('tours','restaurant') NOT NULL,
	`vendorName` varchar(255) NOT NULL,
	`vendorAddress` text NOT NULL,
	`vendorRegistrationNo` varchar(100),
	`vendorEmail` varchar(320) NOT NULL,
	`vendorPhone` varchar(50) NOT NULL,
	`vendorWhatsapp` varchar(50),
	`contactPersonName` varchar(255) NOT NULL,
	`contactPersonTitle` varchar(100),
	`partnershipLevel` varchar(50) NOT NULL,
	`vendorSignature` text,
	`signedAt` timestamp,
	`status` enum('draft','pending','signed','delivered') NOT NULL DEFAULT 'pending',
	`pdfUrl` text,
	`pdfKey` varchar(255),
	`emailSent` boolean DEFAULT false,
	`emailSentAt` timestamp,
	`whatsappSent` boolean DEFAULT false,
	`whatsappSentAt` timestamp,
	`effectiveDate` timestamp,
	`ipAddress` varchar(45),
	`userAgent` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agreements_id` PRIMARY KEY(`id`)
);
